d = {
    'A balanced sword with a slight curve, favored by sailors for swift, slashing strikes.': '一把略带弧度的平衡剑，受到水手青睐，适合快速的斩击。',
    'A basic leather vest, often worn by sailors, providing minimal defense against scrapes and light blows.': '一件基本的皮革背心，水手常穿，提供最小程度的防护，可防止划伤和轻微打击。',
    'A basic, well-used sword, functional but worn from frequent use in rough seas.': '一把基本的、经常使用的剑，虽然实用，但由于在恶劣海况下的频繁使用而磨损。',
    'A battle permit issued by your nation. Allows you to legally attack fleet from other nations.': '由国家颁发的战斗许可，允许你合法攻击其他国家的舰队。',
    "A beautiful fan made from the feathers of a peacock, known for their vibrant colors. It's a symbol of beauty, grace, and elegance, often used as a decorative accessory.": '一把用孔雀羽毛制成的美丽扇子，以其鲜艳的色彩闻名。它象征着美丽、优雅和高贵，常用作装饰配件。',
    'A blade that sings when swung.': '挥动时会发出歌声的剑。',
    'A brooch featuring a deep red garnet gemstone, often used as a decorative accessory. Known for its rich color, it symbolizes passion and courage.': '一枚镶嵌深红色石榴石的胸针，常用作装饰配件，以其浓郁的颜色著称，象征激情和勇气。',
    'A coat made from rich, soft velvet fabric, known for its luxurious texture. It is often worn in formal settings and signifies wealth and high status.': '一件由丰富柔软的天鹅绒面料制成的外套，以其奢华的质感闻名，通常在正式场合穿着，象征财富和高地位。',
    'A combination of plate and chain armor, covering the chest and vital areas while leaving the limbs more exposed. It offers increased protection over chain mail, especially against strikes to the torso, without sacrificing too much mobility.': '结合了板甲和锁子甲的护甲，覆盖胸部和关键部位，同时四肢暴露更多。相比锁子甲，它提供了更高的保护，尤其是对躯干的打击，同时不会牺牲太多机动性。',
    'A crude, heavy sword suited for basic defense, often found on the docks.': '一把粗糙而沉重的剑，适合基本防御，通常在码头可以找到。',
    'A curved saber once wielded by a legendary pirate king.': '一把曾被传奇海盗王使用过的弯刀。',
    'A decorative item designed to hold candles. Made from various metals or fine materials, it often has an elegant or artistic design, adding charm to any setting.': '用于放置蜡烛的装饰物，由各种金属或精致材料制成，通常具有优雅或艺术的设计，为任何环境增添魅力。',
    "A delicate bangle with a design inspired by the sea, often featuring seashells or aquatic motifs. It's a symbol of the mystical and enchanting world beneath the waves.": '一只以大海为灵感设计的精美手镯，常以贝壳或水生图案为特色。它象征着波浪下神秘而迷人的世界。',
    'A delicate shawl made from fine silk, often draped over the shoulders. It is a symbol of elegance and sophistication, suitable for both formal and casual occasions.': '一件用优质丝绸制成的精美披肩，通常披在肩上。它是优雅和精致的象征，适合正式和休闲场合。',
    'A durable, well-crafted sword known for its sturdiness and dependable cutting power.': '一把耐用且工艺精良的剑，以其坚固性和可靠的切割力而闻名。',
    "A fine comb crafted from platinum, often used for styling hair. Known for its durability and elegance, it's a luxurious item associated with high society.": '一把由铂金制成的精美梳子，常用于打理头发。以其耐用性和优雅著称，是与上流社会相关的奢侈品。',
    "A finely crafted bracelet made of solid gold. It's a symbol of wealth and sophistication, often worn on special occasions.": '一只由纯金制成的精美手镯。它是财富和精致的象征，常在特殊场合佩戴。',
    'A full suit of rigid, interlocking metal plates that covers the entire body. It offers the highest level of protection, making it ideal for heavy combat situations, but can be cumbersome and reduce agility, especially on long sea voyages.': '一套覆盖全身的刚性金属板甲，提供最高级别的保护，非常适合激烈的战斗场合，但可能笨重且降低敏捷性，特别是在长时间的海上航行中。',
    'A high precision instrument used for  measuring longitude and latitude.': '用于测量经度和纬度的高精度仪器。',
    'A highly ornate and protective set of armor, designed for high-ranking naval officers.': '一套高度装饰性且具有防护性的盔甲，为高级海军军官设计。',
    "A legendary sword said to command the sea's power.": '一把传说中可以控制海洋力量的传奇之剑。',
    'A lightweight and soft scarf made from luxurious silk, often worn as a fashion statement or for warmth. It is a symbol of refinement and grace.': '一条由奢华丝绸制成的轻便柔软的围巾，常作为时尚宣言或保暖之用。它是精致和优雅的象征。',
    'A long, straight sword forged with rare metals from the ocean floor.': '一把用海底稀有金属锻造的长直剑。',
    'A low precision instrument used for measuring longitude and latitude.': '用于测量经度和纬度的低精度仪器。',
    'A luxurious coat made from the fur of the ermine, often worn by royalty and nobility. It is a symbol of wealth, prestige, and high social rank.': '一件由貂皮制成的奢华外套，常被皇室和贵族穿戴。它是财富、声望和高社会地位的象征。',
    'A luxurious ring set with a brilliant diamond, symbolizing wealth and prestige. Known for its sparkling beauty, it can serve as a valuable treasure or a sign of high status.': '一枚镶有璀璨钻石的奢华戒指，象征财富和声望。以其闪耀的美丽而闻名，可以作为珍贵的宝物或高地位的象征。',
    'A magnificent crown adorned with jewels and precious metals. Worn by royalty or high-ranking officials, it represents ultimate power and authority.': '一顶镶有珠宝和贵金属的华丽皇冠。由皇室或高级官员佩戴，象征着至高无上的权力和威严。',
    'A necklace featuring a stunning sapphire gemstone, renowned for its deep blue hue. It signifies wisdom and nobility and is often worn by those of high status.': '一条镶有迷人蓝宝石的项链，以其深蓝色调闻名。它象征智慧和高贵，通常由地位显赫的人佩戴。',
    'A potent and deadly substance designed to eliminate rats. When placed in areas infested with rodents, it quickly eliminates the pests, helping to protect food supplies and maintain cleanliness on board. However, it must be handled with care due to its toxicity.': '一种用于消灭老鼠的强效毒物。当放置在鼠患严重的区域时，它可以快速消灭害虫，有助于保护食品供应并保持船上的清洁。然而，由于其毒性，必须小心处理。',
    'A powerful scepter adorned with a radiant ruby at its head. It is often a symbol of rulership, strength, and command, associated with noble or royal figures.': '一根顶部镶有光辉红宝石的权杖。它通常象征着统治力、力量和指挥能力，与贵族或皇室人物相关。',
    'A precious blue gemstone, often used in jewelry. It symbolizes wisdom and loyalty, prized for its beauty and rarity.': '一种珍贵的蓝色宝石，常用于珠宝中。它象征智慧和忠诚，以其美丽和稀有而备受推崇。',
    'A rare and sacred oil known for its calming properties. When applied to the sea or cast upon the winds, it soothes the fury of storms, calming turbulent waters and dispelling violent weather. Sailors and captains use it as a last resort to ensure safe passage through treacherous seas.': '一种稀有而神圣的油，以其镇静特性而闻名。当应用于海面或撒在风中时，它可以平息暴风的愤怒，平静波涛汹涌的海水并驱散恶劣天气。水手和船长将其作为最后的手段，以确保通过危险海域的安全。',
    'A simple shirt of chainmail, offering better protection than leather, but heavier and harder to move in.': '一件简单的锁子甲，比皮革提供更好的保护，但更重且行动更困难。',
    'A sleek, silver sword engraved with celestial patterns.': '一把刻有天体图案的流线型银剑。',
    'A slightly longer sword, good for both thrusting and slicing, preferred by more skilled combatants.': '一把稍长的剑，既适合刺击又适合切割，更受技术娴熟的战斗人员青睐。',
    "A small decorative box made from malachite, a green stone known for its beautiful swirls. It's perfect for storing small valuables and prized items.": '一个由孔雀石制成的小型装饰盒，这种绿色石材以其美丽的漩涡纹而闻名。非常适合存放小型贵重物品。',
    'A small portable watch.': '一只小型便携式怀表。',
    'A small, ornate chest often used to store precious items and gems. Its intricate carvings and fine craftsmanship make it a highly sought-after collectible.': '一个小巧华丽的箱子，通常用来存放珍贵物品和宝石。其精致的雕刻和精湛的工艺使之成为备受追捧的收藏品。',
    'A sword that channels the power of the storm.': '一把引导风暴力量的剑。',
    'A trade permit issued by your nation. Allows you to  buy and sell in allied ports with 10% discount.': '由国家颁发的贸易许可，允许你在盟国港口买卖商品并享受 10% 的折扣。',
    'A traditional dress made from fine silk or satin, often embroidered with intricate patterns. It is a symbol of grace and elegance, typically worn for formal occasions or ceremonies.': '一件由优质丝绸或缎子制成的传统礼服，通常绣有复杂图案。它是优雅和高贵的象征，通常用于正式场合或仪式。',
    'A vital remedy for scurvy. Consuming it regularly helps prevent and cure the debilitating effects of scurvy, restoring health and vitality to sailors during long voyages at sea.': '一种治疗坏血病的重要药物。经常服用可以预防和治疗坏血病的衰弱症状，在长期海上航行中恢复水手的健康和活力。',
    'An optical instrument that allows you to see further at sea.': '一种可以让你在海上看到更远的光学仪器。',
    "Not only does a cat make a nice pet, but it'll keep your ship rat-free!": '猫不仅是一个好宠物，还能让你的船免受老鼠侵害！',
    'The most precise and reliable instrument used for measuring longitude and latitude.': '用于测量经度和纬度的最精确和可靠的仪器。',
    'This bulky but highly durable plate armor is crafted to withstand the harsh conditions of both land and sea.': '这种笨重但非常耐用的板甲专为应对陆地和海上恶劣环境而制作。',
}
print(d)